const { Router } = require('express');
const { db } = require('./../firebase');
const admin = require("firebase-admin");


const router = Router();

// /games Return array with all previous game-objects (GET)
router.get('/', async (req, res) => {

    try {

        let games = [];
        
        // Get all games from firebase
        let snapshot = await db
        .collection('games')
        .get();

        snapshot.forEach(game => {
            games.push(game.data())
        })

        res.send(games);
        
    } 
    catch (err) {

        res.status(500).send(err);
        
    }
})

// /games Save a game-object to firestore collection games (POST)
router.post('/', async (req, res) => {
    
    let game = {
            id: db // Set id as autogenerated firestore-id
                .collection('games')
                .doc()
                .id,
            timeStamp: admin.firestore.Timestamp.now(),
            contestants: [
                { contestant1: req.body.contestants[0].contestant1 },
                { contestant2: req.body.contestants[1].contestant2 }
            ],
            winnerId: req.body.winnerId
        }
    
    try {

        await db
        .collection('games')
        .doc()
        .set(game);

        res.status(201).send(game)

    }
    catch(err) {

        res.status(500).send(err);

    }
})

module.exports = router;